### ISSUE TITLE
Levels System

### ISSUE THREAD

**Issue by ethanlaj** [Bro-Time/Bro-Time-Server#565]
Everyone will keep their current level, but now it will be easier to award bro bits to active chatters (in the future?) easily

**Comment by cloewen8** [comment]
It would be awesome if there was an option to import levels from other bots!

**Comment by gt-c** [comment]
This was closed, if we ever do this, it’ll be on another bot.

**Comment by gt-c** [comment]
Because of how ethan really just wanted it to be for Bro Time, and I didn’t really want a public levels feature as other bots already have this (mee6 is a huge bot with hundreds of thousands of servers relying on its levels feature). So me and Ethan agreed that if we did do this, it would be on a seperate bot completely limited to Bro Time.
